version: '3.8'

services:
  # Uvicorn web server - API services
  web:
    build: .
    container_name: handcrafters_api
    # Wait until the database is initialized, then start the server
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; uvicorn Server.main:app --host 0.0.0.0'
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/handcrafters_db
    volumes:
      - .:/Server
    ports:
      - "8008:8000"
    depends_on:
      - database
    restart: always
    networks:
      - default
      
    # Postgres database
  database:
      image: postgres:13-alpine
      container_name: handcrafters_database
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=handcrafters_db
      volumes:
        - database_data:/var/lib/postgresql/data
      expose:
        - 5432
      networks:
        - default

# Persistent data
volumes:
  database_data: